### ISSUE TITLE
GTX 1080ti  x 1 , memory shortage

### ISSUE THREAD

**Issue by whria78** [hujie-frank/SENet#33]
Hello. Thank you for sharing fantastic SENet model.

I tried to train with my 1080ti. 11Gb ram.

I succeeded to train SE resnet 101 (train batch 5).

But I failed to train SENet , or SE resnet 152 even though I set the train_batch to 1.

I used bvlc caffe and patched with this repo.

11Gb GPU memory is not enough to train SENet??

Thank you.

**Comment by whria78** [comment]
I tried to update BVLC caffe with the following tutorial, and I can get some more GPU memory, but still out of memory for SENet.

http://blog.yjxiong.me/archives/403
https://github.com/yjxiong/caffe/

By adding MemoryOptimize_v2 function to BVLC Caffe, I could increase train_batch from 5 to 6 in case of SE resnet 101.

But, there is still out of memory in case of SENet (SE resnet 152)

Should I bought Titan X ?

**Comment by hujie-frank** [comment]
Due to the existence of BN, the performance could be hurt when the training batch-size is too small. In general, the batch-size is set to 32 on each GPU. 

As for the GPU memory consumption, there are many optimizable works need to be done on BVLC/caffe.  Although there are some open source optimized caffe,  the saving resources are not remarkable. There is still a great amount of memory occupation to be optimized. Besides that, [sublinear](https://arxiv.org/abs/1604.06174) memory strategy is required for training huge networks, like SENet. By the way, it's not easy to correctly implement on caffe. Our internal version is not open source, so maybe using MXNet in which has already implemented is a good choice.

**Comment by whria78** [comment]
Thank you very much. I hope there will be more optimization on caffe, or GPU with large ram will be available. :)

**Comment by whria78** [comment]
Hello, I found that if I compiled Caffe without cuDNN, I could train SENet even with GTX 1070, 8GB.
It may be helpful who try to finetune the most outstanding CNN model, SENet. :)

**Comment by whria78** [comment]
Another option :
https://developer.ibm.com/linuxonpower/2018/10/11/exploration_lms_powerai_ibm_caffe/
https://github.com/ibmsoe/caffe/tree/master-lms

**Comment by whria78** [comment]
In addition, there may be some advance in NVCaffe (0.17.2). Now we can train SENet with 8GB GPU ram.
