### ISSUE TITLE
cannot build caffe with axpy_layer (NVIDIA/caffe)

### ISSUE THREAD

**Issue by MartinHahner88** [hujie-frank/SENet#43]
Hi, 

first off all, congratulations to the great result on ImageNet!

I want to try your architecture in my Master Thesis,
where I try to distinguish action forces from regular pedestrians based on their appearance in my own dataset.

Here is what I did:

I added your provided files to my NVIDIA caffe flavour from
https://github.com/NVIDIA/caffe
in
src/caffe/layers
and
include/caffe/layers
respectively.

Then I ran "make clean".
But when I want to build caffe with "make all -j16" I get the following build error?

In file included from src/caffe/layers/axpy_layer.cpp:8:0:
./include/caffe/layers/axpy_layer.hpp:25:36: error: wrong number of template arguments (1, should be 2)

What do I also need to change in order for a successful build?

**Comment by hujie-frank** [comment]
In order to support mixed precision training, the NVIDIA/caffe replaced the original "template\<typename Dtype>" with "template<typename Ftype, typename Btype>" in which the precision of forward and backward can be specified respectively. 

You can use the BVLC/caffe or modify the template in Axpy layer to cater for the NVIDIA/caffe. Additionally, you can replace all the Axpy layer in prototxt with Scale layer and Elementwise summation layer as there is no parameter in Axpy layer.

**Comment by MartinHahner88** [comment]
OK, I will go the easy way then and switch to BVLC/caffe for my experiments with your SENet architecture,
but thanks for the insightful comments and modification hints, too.

**Comment by tleers** [comment]
> 
> 
> In order to support mixed precision training, the NVIDIA/caffe replaced the original "template<typename Dtype>" with "template<typename Ftype, typename Btype>" in which the precision of forward and backward can be specified respectively.
> 
> You can use the BVLC/caffe or modify the template in Axpy layer to cater for the NVIDIA/caffe. Additionally, you can replace all the Axpy layer in prototxt with Scale layer and Elementwise summation layer as there is no parameter in Axpy layer.

How should we replace Axpy layers by Scale and Elementwise? Would it be possible to see what the new .prototxt file should look like? Or just an example of one Axpy layer replaced with its scale and elementwise alternative?

Thanks a lot!
