### ISSUE TITLE
About Parameterized weights in S-E structure

### ISSUE THREAD

**Issue by BOBrown** [hujie-frank/SENet#55]
S-E structure also illustrates that the distribution wi(feature map weights) across different classes is nearly identical in lower layers, which probably implies that parameterized weights wi of feature maps in these layers are independent with input sample. But what's the points of using this parameterized weights rather than data-Independent weights？

Thank you for your reply.

**Comment by lishen-shirley** [comment]
The weights (i.e. wi) here introduce input-dependent (the input is a sample) dynamics (please see the section 3.2). The visualisation shown in the paper is based on class statisics, where the lower layers tend to produce the weights in a **class-agnostic** manner.  But the weights for each sample in a class could be varied due to intraclass diversity.
