### ISSUE TITLE
Does SE-Net work in other network architectures or in detection tasks? 

### ISSUE THREAD

**Issue by cai-y13** [hujie-frank/SENet#7]
Does SE-Net work in other network architectures like VGG, Alexnet or some other networks besides GoogLeNet Inception and ResNet?

Besides, does SE module work on detection frameworks or models like SSD, Faster RCNN, etc? I have add the Squeeze and Excitation module in SSD ( aiming to strengthen the 6 features), but it doesn't seem to work. 

Looking forward to your suggestions, thanks so much.

**Comment by hujie-frank** [comment]
It also works in VGG, AlexNet networks as the SE module is not restricted in specific architecture. 

We conducted experiments on COCO detection task by Faster-RCNN, using SE-ResNet-50 and SE-ResNet-101. Both achieved great improvements over their non-SE counterparts.  We haven't  performed  experiments in SSD yet, but I think it is capable of benefiting the performance due to the characteristic 
 of feature enhancement.

**Comment by zimenglan-sysu-512** [comment]
hi @hujie-frank,
do you have trained SE-Net in googlenet?
thanks

**Comment by hujie-frank** [comment]
We did not empirically cooperate SE with GoogleNet as the SE-BN-Inception is sufficient for validating the effectiveness of SE without skip-layer.
